### ISSUE TITLE
Retirar a classe PicPay do __init__.py

### ISSUE THREAD

**Issue by Mdslino** [MarcusMann/python-picpay#10]
Seria uma boa criar um arquivo picpay.py e colocar o código do __init__.py lá e só referênciar a classe no __init__.py, fica um pouco mais óbvio de onde estariam as coisas.

**Comment by marcuxyz** [comment]
Bem notado, as vezes eu esqueço que a partir do Python 3.4 o __init__.py não é mais obrigatório. Contudo o próprio **poetry** que criou!

Vou fazer a modificação, pois achei interessante, logo mais irei rodar os testes, abro um PR e te marco para você avaliar.

Obrigado @Mdslino
