### ISSUE TITLE
Interface assincrona

### ISSUE THREAD

**Issue by Mdslino** [MarcusMann/python-picpay#9]
Como a ideia da lib é ser agnóstica a framework, uma boa ideia seria ter uma interface assíncrona para se utilizar com asyncio. Uma forma simples de resolver isso seria utilizar o httpx no lugar do requests e criar uma nova classe que suporte asyncio

**Comment by marcuxyz** [comment]
Temos ver que como isso se comportaria, a ideia é muito boa, visto que temos:
* fastapi
* starlette
* responder

Entre outros frameworks que são Async... Como você sugeriu criar uma classe ambígua para resolver o problema, eu sugiro a finalização da lib, resolução de bugs e depois implementar essa feature o que acha?

**Comment by Mdslino** [comment]
Sim concordo. Foi mais para mapear alguns pontos de melhoria que eu identifiquei.

Inclusive se quiser dar uma olhada no [httpx](https://www.python-httpx.org/) a interface é bem parecida com o requests e é o substituto natural dele. O Kenneth Reitz inclusive deu uma congelada no Requests 3 pois o httpx já tinha implementado tudo que ele pensava em fazer.

**Comment by marcuxyz** [comment]
Confesso que eu não conhecia o httpx @Mdslino , vou da uma olhada, você gostaria de pegar essa feature?

**Comment by Mdslino** [comment]
Sim, posso pegar
